export const USERS_FETCH_REQUESTED = "USERS_FETCH_REQUESTED";
export const USERS_FETCH_SUCCEEDED = "USERS_FETCH_SUCCEEDED";
export const USERS_FETCH_FAILED = "USERS_FETCH_FAILED";

export const PAGE_UPDATE_REQUESTED = "PAGE_UPDATE_REQUESTED";
export const PAGE_UPDATE_SUCCEEDED = "PAGE_UPDATE_SUCCEEDED";
export const PAGE_UPDATE_FAILED = "PAGE_UPDATE_FAILED";
