export const USERS_FETCH_REQUESTED = "USERS_FETCH_REQUESTED";
export const USERS_FETCH_SUCCEEDED = "USERS_FETCH_SUCCEEDED";
export const USERS_FETCH_FAILED = "USERS_FETCH_FAILED";

export const FETCH_USER_BY_ID_REQUESTED = "FETCH_USER_BY_ID_REQUESTED";
export const FETCH_USER_BY_ID_SUCCEEDED = "FETCH_USER_BY_ID_SUCCEEDED";
export const FETCH_USER_BY_ID_FAILED = "FETCH_USER_BY_ID_FAILED";
