export { default as LogoImage } from "./svg/logo.svg";
export { default as GlobeImage } from "./svg/globe.svg";
export { default as BurgerImage } from "./svg/burger.svg";
export { ReactComponent as PhoneImage } from "./svg/phone.svg";
export { ReactComponent as LocationImage } from "./svg/location.svg";
export { default as UaFlag } from "./images/ua-flag.png";
export { default as EnFlag } from "./images/uk-flag.png";
export { default as BannerImage } from "./images/banner.jpg";
export { default as BgImage } from "./images/background.jpg";